### PR TITLE
Corrected Bookmarks call

### PR DESCRIPTION
**Pull request by SDManson**
Bookmarks require apikey and characterID Added characterID

### CODE REVIEW

**Comment by ezet** [comment]
You just removed the bit of code actually performing the request? Please clarify the problem and what you intended to fix.

**Comment by SDManson** [comment]
Sorry for delayed response.... but GetBookmarks requires 2 parameters
Your code.....
return requestAsync<Bookmarks>(relPath, ApiKey);
My fixed code not 100% sure I copied the signature from another call that
required ApiKey and CharacterID
return requestAsync<Bookmarks>(relPath, ApiKey, "characterId", CharacterId);

On Mon, Feb 22, 2016 at 12:39 PM, Lars Kristian Dahl <
notifications@github.com> wrote:

> Closed #63 <https://github.com/ezet/evelib/pull/63>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ezet/evelib/pull/63#event-560144951>.
>



-- 
Scotty

**Comment by ezet** [comment]
Uhm, did you look at your code? https://github.com/SDManson/evelib/commit/b61b959bcf67c2227b78fe74c404aa4f34cbe548
You've just removed a line.

I'll have another look.

**Comment by ezet** [comment]
This has been fixed in the newest release, available on nuget.
https://github.com/ezet/evelib/releases/tag/EveXml_v3.0.4

**Pull request closed without merging**
